#%RAML 1.0 Library
types:
  Podcast:
    properties:
      author: Author
      title: string
      duration: number
  Author:
    properties:
      firstName: string
      lastName: string
      discography: Podcast[]